version: 0.2

env:
  variables:
    NODE_ENV: production
    DISABLE_OPENCOLLECTIVE: true
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - pip3 install aws-sam-cli --upgrade --user
  pre_build:
    commands:
      - NODE_ENV=development npm ci
      - npm audit --audit-level=moderate
      - npm run lint
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      # Empaqueta SOLO la layer en un zip listo para Lambda Layers
      # Normalmente SAM deja el contenido de la layer en .aws-sam/build/SharpHEICLayer/
      - cd .aws-sam/build/SharpHEICLayer
      - zip -r ../SharpHEICLayer.zip .
      - cd ../../..

artifacts:
  files:
    - .aws-sam/build/SharpHEICLayer.zip
    - .aws-sam/build/template.yaml

cache:
  paths:
    - '/root/.npm/**/*'
